### PR TITLE
Support current kustomize release assets url

### PR DESCRIPTION
**Pull request by dan-slinky-ckpd**
They don't make it easy. They've changed it more than once. This will be compatible with the current release process.

### CODE REVIEW

**Comment by karancode** [comment]
Hi @dan-slinky-ckpd, thank you so much for the contribution.
I checked for this path and the issue is that this will break actions running with older versions of kustomize (for ex: `3.1.0`).
We will need to fix it to have backward compatibility as well...
Or can we just let actions using `@master` crash🤔

**Comment by dan-slinky-ckpd** [comment]
I did have the same thought. My opinion was that people should probably pin their actions anyway, if you're using `@master` you should expect things might break 🤷‍♂️ 

To maintain backward compatibility I guess we'd need to provide a var for overriding the url? Feels wrong.

**Comment by karancode** [comment]
Passing url for download might be little troublesome. I was thinking to update the `install_kustomize()` function to check for the version and accordingly choose the URL.

**Comment by dan-slinky-ckpd** [comment]
@karancode PR updated with improved logic and support all the versions.

**Comment by karancode** [comment]
@dan-slinky-ckpd sorry for late reply here. I tried to test this patch and looks like it still fails for newer versions of kustomize (tried with `3.6.1` & `3.1.0`, fails for `3.6.1`). I think some issue with untar.

**Comment by dan-slinky-ckpd** [comment]
@karancode Do you have any more information on the failure? Working here as expected: https://github.com/dan-slinky-ckpd/kustomize-action-testing/runs/849558694?check_suite_focus=true#step:4:3

**Comment by karancode** [comment]
hey @dan-slinky-ckpd really sorry for the false alarm. I checked again and looks like I had mistaken while checking. This change LGMT 👍 
Thanks alot. I will merge this and cut out a new tag! 🎉

**Comment by karancode** [comment]
@dan-slinky-ckpd I have cut out a new tag [v1.1.0](https://github.com/karancode/kustomize-github-action/releases/tag/v1.1.0) with this change 🎉. Thanks again for the contribution! ❤️ 

PS : Please drop ⭐ if you use this! 🙇

**Pull request merged**
